export const products = [
  {
    id: 1,
    sku: "DRN-DJI-MINI4PRO",
    name: "DJI Mini 4 Pro",
    brand: "DJI",
    category: "Drones",
    description:
      "Dron compacto con cámara 4K HDR y detección de obstáculos omnidireccional.",
    longDescription:
      "El DJI Mini 4 Pro combina portabilidad, calidad de imagen profesional y sistemas avanzados de seguridad en vuelo. Es ideal para creadores que necesitan un dron liviano, potente y fácil de transportar.",
    price: 759,
    oldPrice: 899,
    slug: "dji-mini-4-pro",
    categorySlug: "drones",
    stock: 12,
    rating: 4.9,
    reviews: 128,
    image: "/images/products/dji-mini-4-pro/main.png",
    images: [
      "/images/products/dji-mini-4-pro/main.png",
      "/images/products/dji-mini-4-pro/angle.png",
      "/images/products/dji-mini-4-pro/side.png",
    ],
    specs: [
      "Cámara 4K HDR",
      "Detección omnidireccional",
      "Hasta 34 minutos de vuelo",
      "Peso menor a 249 g",
    ],
    colors: ["Gris claro"],
    isNew: true,
    isOffer: false,
    featured: true,
  },
  {
    id: 2,
    sku: "DRN-DJI-AIR3S",
    name: "DJI Air 3S",
    brand: "DJI",
    category: "Drones",
    description:
      "Dron avanzado con doble cámara, gran autonomía y captura aérea de alto nivel.",
    longDescription:
      "DJI Air 3S está pensado para pilotos y creadores que buscan una experiencia aérea más completa, con mejor rendimiento de cámara, estabilidad y autonomía para producciones exigentes.",
    price: 1099,
    oldPrice: 1299,
    slug: "dji-air-3s",
    categorySlug: "drones",
    stock: 8,
    rating: 4.8,
    reviews: 96,
    image: "/images/products/dji-air-3s/main.png",
    images: [
      "/images/products/dji-air-3s/main.png",
      "/images/products/dji-air-3s/angle.png",
      "/images/products/dji-air-3s/side.png",
    ],
    specs: [
      "Sistema de doble cámara",
      "Video 4K de alta calidad",
      "Vuelo inteligente",
      "Autonomía extendida",
    ],
    colors: ["Gris"],
    isNew: true,
    isOffer: false,
    featured: true,
  },
  {
    id: 3,
    sku: "DRN-DJI-MAVIC3PRO",
    name: "DJI Mavic 3 Pro",
    brand: "DJI",
    category: "Drones",
    description:
      "Dron profesional con cámara triple y rendimiento premium para producción audiovisual.",
    longDescription:
      "DJI Mavic 3 Pro está diseñado para creadores profesionales que necesitan máxima calidad, control avanzado y una experiencia de vuelo estable en proyectos de alto nivel.",
    price: 1999,
    oldPrice: 2199,
    slug: "dji-mavic-3-pro",
    categorySlug: "drones",
    stock: 5,
    rating: 4.9,
    reviews: 203,
    image: "/images/products/dji-mavic-3-pro/main.png",
    images: [
      "/images/products/dji-mavic-3-pro/main.png",
      "/images/products/dji-mavic-3-pro/angle.png",
      "/images/products/dji-mavic-3-pro/side.png",
    ],
    specs: [
      "Sistema de cámara triple",
      "Captura profesional",
      "Gran rango dinámico",
      "Transmisión de largo alcance",
    ],
    colors: ["Gris oscuro"],
    isNew: false,
    isOffer: true,
    featured: true,
  },
  {
    id: 4,
    sku: "DRN-DJI-AVATA2",
    name: "DJI Avata 2",
    brand: "DJI",
    category: "Drones",
    description:
      "Dron FPV compacto para vuelos inmersivos, dinámicos y tomas llenas de acción.",
    longDescription:
      "DJI Avata 2 ofrece una experiencia FPV inmersiva, ideal para pilotos que buscan tomas ágiles, vuelos creativos y una sensación de control más cercana a la acción.",
    price: 999,
    oldPrice: null,
    slug: "dji-avata-2",
    categorySlug: "drones",
    stock: 10,
    rating: 4.7,
    reviews: 75,
    image: "/images/products/dji-avata-2/main.png",
    images: [
      "/images/products/dji-avata-2/main.png",
      "/images/products/dji-avata-2/angle.png",
      "/images/products/dji-avata-2/side.png",
    ],
    specs: [
      "Experiencia FPV",
      "Diseño compacto",
      "Protección de hélices",
      "Video ultra estabilizado",
    ],
    colors: ["Negro"],
    isNew: true,
    isOffer: false,
    featured: false,
  },
  {
    id: 5,
    sku: "CAM-DJI-ACTION5PRO",
    name: "DJI Osmo Action 5 Pro",
    brand: "DJI",
    category: "Cámaras",
    description:
      "Cámara de acción resistente con gran calidad de imagen y estabilización avanzada.",
    longDescription:
      "DJI Osmo Action 5 Pro está pensada para deportes, viajes y contenido extremo. Combina resistencia, buena autonomía y captura estable en condiciones exigentes.",
    price: 349,
    oldPrice: 399,
    slug: "dji-osmo-action-5-pro",
    categorySlug: "camaras",
    stock: 15,
    rating: 4.7,
    reviews: 86,
    image: "/images/products/dji-osmo-action-5-pro/main.png",
    images: [
      "/images/products/dji-osmo-action-5-pro/main.png",
      "/images/products/dji-osmo-action-5-pro/angle.png",
      "/images/products/dji-osmo-action-5-pro/side.png",
    ],
    specs: [
      "Video 4K",
      "Estabilización avanzada",
      "Pantalla frontal",
      "Resistente al agua",
    ],
    colors: ["Negro"],
    isNew: false,
    isOffer: true,
    featured: true,
  },
  {
    id: 6,
    sku: "CAM-GOPRO-HERO13",
    name: "GoPro Hero 13 Black",
    brand: "GoPro",
    category: "Cámaras",
    description:
      "Cámara de acción versátil, resistente y lista para capturar aventuras en alta calidad.",
    longDescription:
      "GoPro Hero 13 Black es una cámara de acción ideal para creadores deportivos, viajeros y usuarios que necesitan resistencia, calidad y facilidad de uso.",
    price: 399,
    oldPrice: null,
    slug: "go-pro-hero-13-black",
    categorySlug: "camaras",
    stock: 11,
    rating: 4.6,
    reviews: 112,
    image: "/images/products/gopro-hero-13-black/main.png",
    images: [
      "/images/products/gopro-hero-13-black/main.png",
      "/images/products/gopro-hero-13-black/angle.png",
      "/images/products/gopro-hero-13-black/side.png",
    ],
    specs: [
      "Video de alta resolución",
      "Diseño resistente",
      "Estabilización digital",
      "Pantalla frontal",
    ],
    colors: ["Negro"],
    isNew: true,
    isOffer: false,
    featured: false,
  },
  {
    id: 7,
    sku: "GMB-DJI-RS4",
    name: "DJI RS 4",
    brand: "DJI",
    category: "Gimbals",
    description:
      "Estabilizador profesional para cámaras mirrorless y producciones exigentes.",
    longDescription:
      "DJI RS 4 está diseñado para filmmakers y creadores que necesitan movimientos fluidos, control preciso y una herramienta confiable para producción profesional.",
    price: 549,
    oldPrice: 649,
    slug: "dji-rs-4",
    categorySlug: "gimbals",
    stock: 7,
    rating: 4.8,
    reviews: 55,
    image: "/images/products/dji-rs-4/main.png",
    images: [
      "/images/products/dji-rs-4/main.png",
      "/images/products/dji-rs-4/angle.png",
      "/images/products/dji-rs-4/side.png",
    ],
    specs: [
      "Estabilización profesional",
      "Diseño compacto",
      "Carga útil alta",
      "Controles avanzados",
    ],
    colors: ["Negro"],
    isNew: false,
    isOffer: true,
    featured: true,
  },
  {
    id: 8,
    sku: "GMB-DJI-RS4MINI",
    name: "DJI RS 4 Mini",
    brand: "DJI",
    category: "Gimbals",
    description:
      "Gimbal compacto y liviano para creadores que buscan movilidad y precisión.",
    longDescription:
      "DJI RS 4 Mini es una opción ideal para creadores de contenido que necesitan un estabilizador fácil de transportar, potente y rápido de configurar.",
    price: 369,
    oldPrice: null,
    slug: "dji-rs-4-mini",
    categorySlug: "gimbals",
    stock: 9,
    rating: 4.7,
    reviews: 42,
    image: "/images/products/dji-rs-4-mini/main.png",
    images: [
      "/images/products/dji-rs-4-mini/main.png",
      "/images/products/dji-rs-4-mini/angle.png",
      "/images/products/dji-rs-4-mini/side.png",
    ],
    specs: [
      "Compacto y liviano",
      "Control preciso",
      "Ideal para creadores",
      "Montaje rápido",
    ],
    colors: ["Negro", "Blanco"],
    isNew: true,
    isOffer: false,
    featured: false,
  },
  {
    id: 9,
    sku: "AUD-DJI-MIC2",
    name: "DJI Mic 2",
    brand: "DJI",
    category: "Audio",
    description:
      "Sistema de micrófono inalámbrico para entrevistas, vlogs y producción móvil.",
    longDescription:
      "DJI Mic 2 permite capturar audio claro y confiable en movimiento. Es ideal para creadores, periodistas, entrevistas, grabaciones en exteriores y contenido social.",
    price: 219,
    oldPrice: 249,
    slug: "dji-mic-2",
    categorySlug: "audio",
    stock: 18,
    rating: 4.8,
    reviews: 93,
    image: "/images/products/dji-mic-2/main.png",
    images: [
      "/images/products/dji-mic-2/main.png",
      "/images/products/dji-mic-2/angle.png",
      "/images/products/dji-mic-2/side.png",
    ],
    specs: [
      "Audio inalámbrico",
      "Estuche de carga",
      "Cancelación de ruido",
      "Grabación interna",
    ],
    colors: ["Negro"],
    isNew: false,
    isOffer: true,
    featured: false,
  }
];